media_extra.settings:
  type: config_object
  label: 'Media Extra settings'
  mapping:
    allowed_image_styles_for_static_image:
      type: sequence
      label: 'Allowed image styles for Media Image formatter'
      sequence:
        type: string
    allowed_image_styles_for_responsive_image:
      type: sequence
      label: 'Allowed image styles for Responsive Media Image formatter'
      sequence:
        type: string
    linkit_profile:
      type: string
      label: 'Linkit profile'

field.formatter.settings.static_image:
  type: field.formatter.settings.media_thumbnail
  label: 'Static image field display format settings'
